version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION) 
      - docker pull fishead/docker-tomcat-maven      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $(ls)
      - docker run --rm -v "$PWD":/app -w /app fishead/docker-tomcat-maven mvn install -Dmaven.test.skip=true
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG


  post_build:
    commands:
      - echo Build completed on `date`
 
artifacts:
  files:
    - 'target/petclinic.war'
    - 'appspec.yml'
    - 'ecsdeployment.template'
    - 'ecsproddeployment.template'
    - 'Dockerfile'
